#!/bin/bash -e

if [ ! -e /etc/ioc-cbc-tools/thermal-conf.xml ]; then
	mkdir -p /etc/ioc-cbc-tools/
	cp /usr/share/ioc-cbc-tools/thermal-conf.xml /etc/ioc-cbc-tools/thermal-conf.xml
fi

while [ ! -e /run/cbc_thermal/cbc_fan0 ]; do
	sleep 1
done
/usr/bin/thermald --no-daemon --ignore-cpuid-check --ignore-default-control --config-file /etc/ioc-cbc-tools/thermal-conf.xml
